//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinDbFirst1
{
    using System;
    using System.Collections.Generic;
    
    public partial class UrunlereGoreDagilimi
    {
        public string ProductName { get; set; }
        public Nullable<int> adet { get; set; }
        public Nullable<decimal> ciro { get; set; }
    }
}
